// Shop item catalog data
export const ShopData = {
    allItems:{
        colors:[
            // ── 기본 프리미엄 (50~70코인) ──
            {id:'c_gold',icon:'🟡',name:'골드',desc:'황금빛 럭셔리',price:60,hex:'#FFD700'},
            {id:'c_neon_green',icon:'💚',name:'네온 그린',desc:'형광 초록',price:50,hex:'#39FF14'},
            {id:'c_ice_blue',icon:'🧊',name:'아이스 블루',desc:'시원한 얼음색',price:50,hex:'#00F5FF'},
            {id:'c_hot_pink',icon:'💗',name:'핫 핑크',desc:'강렬한 분홍',price:50,hex:'#FF69B4'},
            {id:'c_sky',icon:'☁️',name:'스카이 블루',desc:'맑은 하늘색',price:50,hex:'#87CEEB'},
            {id:'c_mint',icon:'🍃',name:'민트',desc:'시원한 민트색',price:50,hex:'#98FB98'},
            {id:'c_peach',icon:'🍑',name:'피치',desc:'복숭아색',price:50,hex:'#FFB6C1'},
            {id:'c_coral',icon:'🪸',name:'코랄',desc:'산호색',price:55,hex:'#FF7F50'},
            {id:'c_lavender',icon:'💜',name:'라벤더',desc:'은은한 보라',price:55,hex:'#E6E6FA'},
            {id:'c_cream',icon:'🍦',name:'크림',desc:'부드러운 크림색',price:45,hex:'#FFFDD0'},
            // ── 중급 (70~100코인) ──
            {id:'c_lava',icon:'🌋',name:'용암 레드',desc:'뜨거운 용암색',price:70,hex:'#FF4500'},
            {id:'c_ocean',icon:'🌊',name:'오션 블루',desc:'깊은 바다색',price:70,hex:'#006994'},
            {id:'c_rose',icon:'🌹',name:'로즈',desc:'우아한 장미색',price:70,hex:'#E84393'},
            {id:'c_neon_pink',icon:'🩷',name:'네온 핑크',desc:'형광 핑크',price:75,hex:'#FF6EC7'},
            {id:'c_neon_blue',icon:'🔵',name:'네온 블루',desc:'형광 파랑',price:75,hex:'#4D4DFF'},
            {id:'c_lime',icon:'🍋',name:'라임',desc:'상큼한 라임색',price:65,hex:'#C4E538'},
            {id:'c_sunset',icon:'🌅',name:'선셋 오렌지',desc:'노을빛',price:80,hex:'#FF8C00'},
            {id:'c_plum',icon:'🍇',name:'플럼',desc:'진한 자두색',price:75,hex:'#8E4585'},
            {id:'c_teal',icon:'🩵',name:'틸',desc:'청록빛',price:70,hex:'#008080'},
            {id:'c_salmon',icon:'🐟',name:'연어 핑크',desc:'부드러운 핑크',price:65,hex:'#FFA07A'},
            // ── 고급 (100~150코인) ──
            {id:'c_galaxy',icon:'🌌',name:'갤럭시 퍼플',desc:'은하수 보라',price:120,hex:'#8A2BE2'},
            {id:'c_ruby',icon:'💎',name:'루비 레드',desc:'보석처럼 빛나는 빨강',price:110,hex:'#E0115F'},
            {id:'c_sapphire',icon:'💠',name:'사파이어',desc:'깊고 푸른 보석색',price:110,hex:'#0F52BA'},
            {id:'c_emerald',icon:'🟢',name:'에메랄드',desc:'영롱한 초록 보석',price:110,hex:'#50C878'},
            {id:'c_diamond',icon:'💍',name:'다이아몬드',desc:'투명하게 빛나는 색',price:150,hex:'#B9F2FF'},
            {id:'c_obsidian',icon:'🖤',name:'옵시디언',desc:'깊고 어두운 검정',price:100,hex:'#1A1A2E'},
            {id:'c_aurora',icon:'🌈',name:'오로라 그린',desc:'북극 오로라색',price:130,hex:'#00FF7F'},
            {id:'c_cherry',icon:'🍒',name:'체리',desc:'달콤한 체리색',price:90,hex:'#DE3163'},
            {id:'c_mocha',icon:'☕',name:'모카',desc:'진한 커피색',price:80,hex:'#967969'},
            {id:'c_silver',icon:'🪙',name:'실버',desc:'은빛 메탈릭',price:100,hex:'#C0C0C0'},
            // ── 최고급 (150~250코인) ──
            {id:'c_hologram',icon:'✨',name:'홀로그램 핑크',desc:'빛에 따라 달라보이는 색',price:200,hex:'#FF61D2'},
            {id:'c_void',icon:'🕳️',name:'보이드 블랙',desc:'텅 빈 우주의 색',price:180,hex:'#0D0D0D'},
            {id:'c_plasma',icon:'⚡',name:'플라즈마 블루',desc:'번개빛 파랑',price:200,hex:'#00BFFF'},
            {id:'c_magma',icon:'🔥',name:'마그마',desc:'지구 핵의 색',price:180,hex:'#FF3E00'},
            {id:'c_frost',icon:'❄️',name:'프로스트',desc:'얼어붙은 서리색',price:170,hex:'#A5F2F3'},
        ],
        hats:[
            // ── 기본 모자 (50~80코인) ──
            {id:'h_cap',icon:'🧢',name:'모자',desc:'귀여운 모자',price:60},
            {id:'h_ribbon',icon:'🎀',name:'리본',desc:'예쁜 리본',price:50},
            {id:'h_flower',icon:'🌸',name:'벚꽃',desc:'봄날의 벚꽃',price:70},
            {id:'h_leaf',icon:'🍀',name:'네잎클로버',desc:'행운의 클로버',price:55},
            {id:'h_mushroom',icon:'🍄',name:'버섯',desc:'귀여운 버섯 모자',price:60},
            {id:'h_cherry2',icon:'🍒',name:'체리',desc:'달콤한 체리 장식',price:55},
            // ── 중급 모자 (80~120코인) ──
            {id:'h_star',icon:'⭐',name:'별',desc:'반짝이는 별',price:80},
            {id:'h_moon',icon:'🌙',name:'초승달',desc:'은빛 초승달',price:85},
            {id:'h_sun',icon:'☀️',name:'태양',desc:'빛나는 태양',price:90},
            {id:'h_rainbow',icon:'🌈',name:'무지개',desc:'알록달록 무지개',price:95},
            {id:'h_cloud',icon:'☁️',name:'구름',desc:'솜사탕 구름',price:80},
            {id:'h_snowflake',icon:'❄️',name:'눈꽃',desc:'겨울 눈꽃 장식',price:85},
            {id:'h_fire2',icon:'🔥',name:'불꽃',desc:'뜨거운 불꽃 머리',price:100},
            {id:'h_lightning',icon:'⚡',name:'번개',desc:'번쩍이는 번개',price:95},
            {id:'h_heart',icon:'❤️',name:'하트',desc:'사랑의 하트',price:80},
            // ── 고급 모자 (120~200코인) ──
            {id:'h_crown',icon:'👑',name:'왕관',desc:'황금 왕관',price:150},
            {id:'h_tiara',icon:'👸',name:'티아라',desc:'공주님의 티아라',price:130},
            {id:'h_halo',icon:'😇',name:'천사 고리',desc:'빛나는 천사 후광',price:140},
            {id:'h_devil',icon:'😈',name:'악마 뿔',desc:'귀여운 악마 뿔',price:140},
            {id:'h_cat',icon:'🐱',name:'고양이 귀',desc:'냥냥 고양이 귀',price:120},
            {id:'h_bunny',icon:'🐰',name:'토끼 귀',desc:'쫑긋 토끼 귀',price:120},
            {id:'h_bear',icon:'🐻',name:'곰 귀',desc:'포근한 곰 귀',price:120},
            {id:'h_fox',icon:'🦊',name:'여우 귀',desc:'영리한 여우 귀',price:125},
            {id:'h_unicorn',icon:'🦄',name:'유니콘 뿔',desc:'마법의 유니콘 뿔',price:160},
            {id:'h_dragon2',icon:'🐉',name:'용 뿔',desc:'전설의 용 뿔',price:180},
            // ── 최고급 모자 (200코인+) ──
            {id:'h_galaxy2',icon:'🌌',name:'은하 왕관',desc:'우주가 담긴 왕관',price:250},
            {id:'h_diamond2',icon:'💎',name:'다이아 왕관',desc:'다이아로 된 왕관',price:300},
            {id:'h_phoenix',icon:'🔶',name:'피닉스 깃털',desc:'불사조 깃털 장식',price:220},
            {id:'h_sakura',icon:'🌺',name:'히비스커스',desc:'열대 꽃 왕관',price:200},
            {id:'h_alien',icon:'👽',name:'외계인 안테나',desc:'삐뽀삐뽀 안테나',price:200},
        ],
        effects:[
            // ── 기본 효과 (60~90코인) ──
            {id:'e_sparkle',icon:'✨',name:'반짝반짝',desc:'별가루 반짝이',price:80},
            {id:'e_heart',icon:'💖',name:'하트 팡팡',desc:'떠다니는 하트',price:70},
            {id:'e_fire',icon:'🔥',name:'불꽃',desc:'뜨거운 불꽃 흔적',price:90},
            {id:'e_bubble',icon:'🫧',name:'비눗방울',desc:'동글동글 비눗방울',price:60},
            {id:'e_leaf',icon:'🍃',name:'나뭇잎',desc:'바람에 날리는 나뭇잎',price:65},
            {id:'e_snow',icon:'🌨️',name:'눈송이',desc:'내리는 하얀 눈',price:70},
            // ── 중급 효과 (90~150코인) ──
            {id:'e_star',icon:'⭐',name:'별똥별',desc:'떨어지는 별똥별',price:100},
            {id:'e_music',icon:'🎵',name:'음표',desc:'흥겨운 음표 파티',price:90},
            {id:'e_lightning',icon:'⚡',name:'전기',desc:'찌릿찌릿 전기 효과',price:110},
            {id:'e_rainbow',icon:'🌈',name:'무지개빛',desc:'무지개색 잔상',price:120},
            {id:'e_petal',icon:'🌸',name:'꽃잎',desc:'흩날리는 벚꽃잎',price:100},
            // ── 고급 효과 (150코인+) ──
            {id:'e_galaxy',icon:'🔮',name:'은하수',desc:'우주 파티클',price:200},
            {id:'e_pixel',icon:'🟩',name:'픽셀붕괴',desc:'픽셀이 흩어지는 효과',price:150},
            {id:'e_ghost',icon:'👻',name:'유령',desc:'투명한 유령 잔상',price:160},
            {id:'e_dragon',icon:'🐉',name:'용의 숨결',desc:'용의 불꽃 아우라',price:250},
        ],
        titles:[
            // ── 기본 칭호 (80~120코인) ──
            {id:'t_ninja',icon:'🥷',name:'그림자 닌자',desc:'은밀하게 출석',price:100,titleText:'그림자 닌자'},
            {id:'t_star',icon:'💫',name:'별에서 온 학생',desc:'우주에서 온 존재',price:100,titleText:'별에서 온 학생'},
            {id:'t_happy',icon:'😊',name:'행복 전도사',desc:'항상 웃는 얼굴',price:80,titleText:'행복 전도사'},
            {id:'t_sleepy',icon:'😴',name:'잠이 최고',desc:'잠만 자고 싶은...',price:80,titleText:'잠이 최고'},
            {id:'t_foodie',icon:'🍕',name:'급식 마스터',desc:'급식이 제일 좋아',price:80,titleText:'급식 마스터'},
            {id:'t_gamer',icon:'🎮',name:'게임의 신',desc:'게임은 나한테 맡겨',price:90,titleText:'게임의 신'},
            {id:'t_artist',icon:'🎨',name:'예술가',desc:'픽셀아트의 달인',price:90,titleText:'예술가'},
            {id:'t_music2',icon:'🎸',name:'음악천재',desc:'리듬을 타는 천재',price:90,titleText:'음악천재'},
            // ── 중급 칭호 (120~180코인) ──
            {id:'t_sun2',icon:'☀️',name:'태양계의 지배자',desc:'태양보다 빛나는',price:150,titleText:'태양계의 지배자'},
            {id:'t_blackhole',icon:'🕳️',name:'블랙홀',desc:'모든 것을 빨아들임',price:150,titleText:'블랙홀'},
            {id:'t_dragon',icon:'🐉',name:'용의 후예',desc:'전설의 용족 후예',price:150,titleText:'용의 후예'},
            {id:'t_wizard',icon:'🧙',name:'마법사',desc:'고대의 마법 사용자',price:140,titleText:'마법사'},
            {id:'t_angel',icon:'😇',name:'천사',desc:'순수한 빛의 존재',price:130,titleText:'천사'},
            {id:'t_demon',icon:'😈',name:'악마',desc:'어둠의 지배자',price:130,titleText:'악마'},
            {id:'t_pirate',icon:'🏴‍☠️',name:'해적왕',desc:'바다의 정복자',price:140,titleText:'해적왕'},
            {id:'t_knight',icon:'⚔️',name:'기사단장',desc:'정의의 검을 휘두르는',price:140,titleText:'기사단장'},
            {id:'t_scientist',icon:'🔬',name:'천재 과학자',desc:'IQ 999의 두뇌',price:130,titleText:'천재 과학자'},
            {id:'t_detective',icon:'🔍',name:'명탐정',desc:'모든 비밀을 파헤치는',price:120,titleText:'명탐정'},
            {id:'t_chef',icon:'👨‍🍳',name:'요리왕',desc:'금손의 요리사',price:120,titleText:'요리왕'},
            {id:'t_athlete',icon:'🏃',name:'체육 만점',desc:'운동신경 만렙',price:120,titleText:'체육 만점'},
            // ── 고급 칭호 (180~250코인) ──
            {id:'t_legend',icon:'🏆',name:'전설의 출석왕',desc:'출석의 전설',price:200,titleText:'전설의 출석왕'},
            {id:'t_emperor',icon:'👑',name:'반장 of 반장',desc:'교실의 진정한 왕',price:200,titleText:'반장 of 반장'},
            {id:'t_phantom',icon:'👤',name:'팬텀',desc:'존재감 없는 존재',price:180,titleText:'팬텀'},
            {id:'t_god',icon:'⚡',name:'전지전능',desc:'모든 것을 아는 자',price:250,titleText:'전지전능'},
            {id:'t_time',icon:'⏰',name:'시간의 지배자',desc:'시간을 멈출 수 있는',price:220,titleText:'시간의 지배자'},
            {id:'t_chaos',icon:'🌀',name:'카오스 메이커',desc:'혼돈을 만드는 자',price:200,titleText:'카오스 메이커'},
            {id:'t_ice',icon:'🧊',name:'얼음 여왕/왕',desc:'냉정한 카리스마',price:180,titleText:'얼음 여왕/왕'},
            {id:'t_flame',icon:'🔥',name:'불꽃 파이터',desc:'열정이 넘치는',price:180,titleText:'불꽃 파이터'},
            // ── 최고급 칭호 (250코인+) ──
            {id:'t_universe',icon:'🌌',name:'우주의 끝',desc:'차원을 넘나드는 존재',price:300,titleText:'우주의 끝'},
            {id:'t_shadow',icon:'🌑',name:'그림자 군주',desc:'어둠 그 자체',price:280,titleText:'그림자 군주'},
            {id:'t_rainbow2',icon:'🌈',name:'무지개 유니콘',desc:'모든 색을 가진 존재',price:280,titleText:'무지개 유니콘'},
            {id:'t_pixel2',icon:'🟩',name:'픽셀의 신',desc:'32x32의 지배자',price:350,titleText:'픽셀의 신'},
        ],
        pets:[
            // ── 기본 동물 (50~80코인) ──
            {id:'p_dog',icon:'🐶',name:'강아지',desc:'충실한 반려견',price:50},
            {id:'p_cat',icon:'🐱',name:'고양이',desc:'도도한 고양이',price:50},
            {id:'p_hamster',icon:'🐹',name:'햄스터',desc:'볼 빵빵 햄스터',price:55},
            {id:'p_rabbit',icon:'🐰',name:'토끼',desc:'깡충깡충 토끼',price:55},
            {id:'p_bird',icon:'🐦',name:'참새',desc:'짹짹짹 참새',price:60},
            {id:'p_turtle',icon:'🐢',name:'거북이',desc:'느긋한 거북이',price:60},
            {id:'p_fish',icon:'🐟',name:'물고기',desc:'둥둥 떠다니는 물고기',price:65},
            {id:'p_bee',icon:'🐝',name:'꿀벌',desc:'윙윙 꿀벌',price:65},
            {id:'p_ladybug',icon:'🐞',name:'무당벌레',desc:'행운의 무당벌레',price:70},
            {id:'p_butterfly',icon:'🦋',name:'나비',desc:'아름다운 나비',price:80},
            // ── 귀여운 동물 (80~120코인) ──
            {id:'p_panda',icon:'🐼',name:'판다',desc:'대나무를 좋아하는',price:80},
            {id:'p_koala',icon:'🐨',name:'코알라',desc:'졸린 코알라',price:85},
            {id:'p_fox',icon:'🦊',name:'여우',desc:'영리한 여우',price:90},
            {id:'p_raccoon',icon:'🦝',name:'너구리',desc:'장난꾸러기 너구리',price:90},
            {id:'p_penguin',icon:'🐧',name:'펭귄',desc:'뒤뚱뒤뚱 펭귄',price:95},
            {id:'p_chick',icon:'🐥',name:'병아리',desc:'삐약삐약 병아리',price:85},
            {id:'p_unicorn',icon:'🦄',name:'유니콘',desc:'무지개 유니콘',price:120},
            {id:'p_pig',icon:'🐷',name:'돼지',desc:'꿀꿀 돼지',price:80},
            {id:'p_frog',icon:'🐸',name:'개구리',desc:'개굴개굴',price:85},
            {id:'p_hedgehog',icon:'🦔',name:'고슴도치',desc:'뾰족뾰족 귀여운',price:100},
            // ── 야생 동물 (120~180코인) ──
            {id:'p_lion',icon:'🦁',name:'사자',desc:'백수의 왕',price:150},
            {id:'p_tiger',icon:'🐯',name:'호랑이',desc:'용맹한 호랑이',price:150},
            {id:'p_bear',icon:'🐻',name:'곰',desc:'거대한 곰',price:130},
            {id:'p_eagle',icon:'🦅',name:'독수리',desc:'하늘의 제왕',price:140},
            {id:'p_wolf',icon:'🐺',name:'늑대',desc:'고독한 늑대',price:145},
            {id:'p_shark',icon:'🦈',name:'상어',desc:'바다의 포식자',price:160},
            {id:'p_croc',icon:'🐊',name:'악어',desc:'무시무시한 악어',price:155},
            {id:'p_elephant',icon:'🐘',name:'코끼리',desc:'거대한 코끼리',price:170},
            {id:'p_flamingo',icon:'🦩',name:'플라밍고',desc:'우아한 플라밍고',price:130},
            {id:'p_parrot',icon:'🦜',name:'앵무새',desc:'말하는 앵무새',price:120},
            // ── 판타지 (180~280코인) ──
            {id:'p_dragon',icon:'🐉',name:'용',desc:'전설의 용',price:280},
            {id:'p_bat',icon:'🦇',name:'박쥐',desc:'어둠의 박쥐',price:180},
            {id:'p_dragon2',icon:'🐲',name:'동양의 용',desc:'신비한 동양 용',price:250},
            {id:'p_scorpion',icon:'🦂',name:'전갈',desc:'독침의 전갈',price:200},
            {id:'p_spider',icon:'🕷️',name:'거미',desc:'거미줄 마스터',price:190},
            {id:'p_octopus',icon:'🐙',name:'문어',desc:'똑똑한 문어',price:210},
            {id:'p_squid',icon:'🦑',name:'오징어',desc:'심해의 오징어',price:200},
            {id:'p_snake',icon:'🐍',name:'뱀',desc:'슬리더링 뱀',price:185},
            {id:'p_lizard',icon:'🦎',name:'도마뱀',desc:'카멜레온 도마뱀',price:190},
            {id:'p_pawprint',icon:'🐾',name:'수수께끼 발자국',desc:'보이지 않는 친구',price:220},
            // ── 전설 (280~400코인) ──
            {id:'p_alien',icon:'👾',name:'외계인',desc:'우주에서 온 친구',price:300},
            {id:'p_robot',icon:'🤖',name:'로봇',desc:'AI 로봇 펫',price:320},
            {id:'p_ufo',icon:'🛸',name:'UFO',desc:'미확인 비행물체',price:350},
            {id:'p_star',icon:'🌟',name:'별',desc:'빛나는 별',price:280},
            {id:'p_skull',icon:'💀',name:'해골',desc:'무서운 해골',price:300},
            {id:'p_ghost',icon:'👻',name:'유령',desc:'떠다니는 유령',price:290},
            {id:'p_pumpkin',icon:'🎃',name:'호박',desc:'할로윈 호박',price:310},
            {id:'p_tooth',icon:'🦷',name:'이빨요정',desc:'이빨을 가져가는',price:280},
            {id:'p_teddy',icon:'🧸',name:'곰인형',desc:'살아 움직이는 인형',price:350},
            {id:'p_matryoshka',icon:'🪆',name:'마트료시카',desc:'러시아 인형',price:400},
        ],
        misc:[
            {id:'r_rename',icon:'✏️',name:'이름변경권',desc:'캐릭터 이름을 1회 변경',price:50,consumable:true},
        ],
    },
};
